package p8;

/* loaded from: classes.dex */
public class q extends l {
    public q() {
        this.f16791d = "VR300";
        this.f16793f = this.f16792e;
        this.p = true;
    }

    @Override // o8.a
    public final String a(boolean z10, String str, String str2, String str3, boolean z11, boolean z12) {
        return "let ssid = \"" + str + "\";\nlet hidden = " + z11 + ";\nlet password = \"" + str2 + "\";\nlet open = " + z12 + ";\nlet maxClients = \"" + str3 + "\";\nlet enabled = " + z10 + ";\nlet exit = setTimeout(() => {\n    clearInterval(temp);\n    clearTimeout(exit);\n    Android.callbackHandle(JSON.stringify({ result: \"timeout\" }));\n}, 25000);\n\nlet temp = setInterval(() => {\n    try {\n        if (document.getElementById('pc-login-btn')) {\n            clearInterval(temp);\n            clearTimeout(exit);\n            Android.callbackHandle(JSON.stringify({ result: \"need_login\" }));\n        } else {\n            Android.callbackHandle(JSON.stringify({ result: \"applying_settings\" }));\n            if (document.getElementById('advanced').className != 'selected') {\n                document.getElementById('advanced').click();\n            } else if (document.getElementById('advanced').className == 'selected' && !document.getElementById('ssid')) {\n                [...document.querySelectorAll('li a span')].filter((span) => span.innerText == 'Wireless Settings')[0].click();\n            } else {\n                if (document.getElementById('load_2g') && document.getElementById('load_2g').className.includes('mode-select')) {\n                    document.getElementById('load_5g').click();\n                } else {\n                    if (document.getElementById('wlEn').checked != enabled) {\n                        document.querySelector('label[for=\"wlEn\"]').click();\n                    }\n                    document.getElementById('ssid').value = ssid;\n                    if (hidden) {\n                        if (!document.getElementById('hideSSID').checked) {\n                            [...document.querySelectorAll('div label span')].filter((span) => span.innerText == 'Hide SSID')[0].click();\n                        }\n                    } else {\n                        if (document.getElementById('hideSSID').checked) {\n                            [...document.querySelectorAll('div label span')].filter((span) => span.innerText == 'Hide SSID')[0].click();\n                        }\n                    }\n                    if (!open) {\n                        document.querySelectorAll('#_sec  li')[2].click(); document.getElementById('wpa2PersonalPwd').value = password;\n                    } else {\n                        document.querySelectorAll('#_sec  li')[1].click();\n                    }\n\n                    if (document.getElementById('save')) {\n                        document.getElementById('save').click();\n                        clearInterval(temp);\n                        clearTimeout(exit);\n                        Android.callbackHandle(JSON.stringify({ result: \"executed\" }));\n                    }\n                }\n            }\n        }\n    } catch (err){ }\n}, 1000);";
    }

    @Override // o8.a
    public final String m() {
        return "let exit = setTimeout(() => {\n    clearInterval(temp);\n    clearTimeout(exit);\n    Android.callbackHandle(JSON.stringify({ result: \"timeout\" }));\n}, 25000);\n\nlet temp = setInterval(() => {\n    try {\n\n        if (document.getElementById('pc-login-btn')) {\n            clearInterval(temp);\n            clearTimeout(exit);\n            Android.callbackHandle(JSON.stringify({ result: \"need_login\" }));\n        } else {\n            Android.callbackHandle(JSON.stringify({ result: \"showing_info\" }));\n            if (document.getElementById('advanced').className != 'selected') {\n                document.getElementById('advanced').click();\n            } else if (document.getElementById('advanced').className == 'selected' && !document.getElementById('ssid')) {\n                [...document.querySelectorAll('li a span')].filter((span) => span.innerText == 'Wireless Settings')[0].click();\n            } else {\n                if (document.getElementById('load_2g') && document.getElementById('load_2g').className.includes('mode-select')) {\n                    document.getElementById('load_5g').click()\n                } else {\n                    if (document.getElementById('ssid')) {\n\n                        Android.callbackHandle(JSON.stringify({\n                            result: \"basic_wifi_info\",\n                            ssidName: document.getElementById('ssid').value,\n                            password: document.getElementById('wpa2PersonalPwd').value,\n                            enabled_5G: document.getElementById('wlEn').checked,\n                            hidden: document.getElementById('hideSSID').checked,\n                            safe: document.getElementById('sec').value != '0',\n                            maxClients: null\n                        }));\n                        clearInterval(temp);\n                        clearTimeout(exit);\n                    }\n                }\n            }\n        }\n    } catch (err){ }\n}, 500);";
    }
}
